version: '3.8'

services:
  postgresql:
    container_name: psql_db
    image: postgres:latest
    environment:
      POSTGRES_USER: qwe
      POSTGRES_PASSWORD: qwe
      PGDATA: /var/lib/data/postgres
    volumes:
      - postgres:/var/lib/data/postgres
    ports:
      - "2345:5432"
    restart: unless-stopped

  app:
    container_name: service
    build: .
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://psql_db:5432/
      SPRING_DATASOURCE_USERNAME: qwe
      SPRING_DATASOURCE_PASSWORD: qwe
    restart: unless-stopped

volumes:
  postgres: