services:
  postgresql:
    container_name: psql_db
    image: postgres:latest
    environment:
      POSTGRES_USER: qwe
      POSTGRES_PASSWORD: qwe
      PGDATA: /var/lib/data/postgres
    volumes:
      - postgres:/var/lib/data/postgres
    ports:
      - "2345:5432"
    restart: unless-stopped

volumes:
  postgres: